name: LeetCode Sync

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync LeetCode
    steps:
      - uses: actions/checkout@v2
      - name: Sync LeetCode
        uses: shuzijun/leetcode-action@v1.1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          user: "your-leetcode-username"
          lang: "cpp"
